### ISSUE TITLE
Loader does not work with IE11

### ISSUE THREAD

**Issue by adamdport** [ngx-translate/http-loader#10]
I'm having trouble getting the loader to work with IE11, 

> ERROR TypeError: Unable to get property 'get' of undefined or null reference

Stepping through it reveals that `this.http` is undefined [here](https://github.com/ngx-translate/http-loader/blob/master/src/http-loader.ts#L14):

    TranslateHttpLoader.prototype.getTranslation = function (lang) {
        return this.http.get("" + this.prefix + lang + this.suffix)
            .map(function (res) { return res.json(); });
    };

The same code works fine for half my team, suggesting that it's a race condition. I suspect that it's related to https://github.com/angular/angular/issues/15501 (which I found after reading through [this issue](https://github.com/angular/angular-cli/issues/5762#issuecomment-295670906)), but I'm not sure.

**Comment by adamdport** [comment]
It seems to work OK if I build in prod mode, `ng serve --prod` or `ng build --prod`. I suspect this is related to JIT v. AOT

**Comment by adamdport** [comment]
I managed to resolve this by including the es6 function polyfill: 

    import 'core-js/es6/function';

**Comment by adamdport** [comment]
The polyfill turned out to be unrelated. This seems to be a race condition. My team ended up moving our `translateService.setDefaultLang(...)` call into a resolver of our eldest component, which makes that code run late enough. It's not a "fix", but it helped me get past this issue.

    path: '', component: AppContainerComponent, resolve: [TranslateResolverService], children: [ ...

    export class TranslateResolverService implements Resolve<any> {
      resolve(): Observable<any> {
      this.translateService.addLangs(["en", "es"]);
      this.translateService.setDefaultLang('en');

**Comment by christrude** [comment]
@adamdport can you elaborate a little more on your fix? I'm trying to match it but when i pull in the translateService to the routes resolver i can't get it to work with `this` and it doesn't bring in it's functions

**Comment by adamdport** [comment]
@christrude In the resolver service, 

    import {TranslateService} from "@ngx-translate/core";
    ...
    constructor(private translateService: TranslateService ...){ ... }
    ...
    resolve(): Observable<any> {
      let translateObservable: Observable<any>;

      this.translateService.addLangs(["en", "es"]);
      this.translateService.setDefaultLang('en');
      translateObservable = this.translateService.use(browserLang.match(/en|es/) ? browserLang : 'en');
      translateObservable.subscribe( () => {
        this.ourCustomLoaderService.loadJsonFile('/assets/i18n/en.json').subscribe((jsonProperties) => {
          this.translateService.setTranslation("en", jsonProperties, true);
        });
      });

Hope that helps, it's been awhile.
