### ISSUE TITLE
Loader does not work with base-href set

### ISSUE THREAD

**Issue by joachimprinzbach** [ngx-translate/http-loader#11]
When having a base-href set, the loader ignores it and can't fetch the i18n files. 

Example: 
`"build": "ng build --aot --prod --base-href /somestring/",`

All requests are ignoring the base-href: "/assets/i18n/en.json" instead of "/somestring/assets/i18n/en.json".
Adding a dot to the prefix ("./assets/i18n/") fixes the problem.

**Comment by desfero** [comment]
+1

**Comment by mzilian** [comment]
+1

**Comment by reikyoushin** [comment]
+1

**Comment by culmat** [comment]
👍

**Comment by DCollart** [comment]
:+1:

**Comment by PunkHaz4rd** [comment]
Is it gonna be merged soon ? it's been 2 month that there's a fix already.

**Comment by pgossmann** [comment]
How do I workaround this?
too bad that this simple fix is not merged. I wish I would know how to help.

**Comment by GoshaFighten** [comment]
@pgossmann Provide your own `TranslateLoader`:

``` TypeScript
TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
}),
```

``` TypeScript
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/');
}
```
