### ISSUE TITLE
Change log not clearly stating the move from Http to HttpClient

### ISSUE THREAD

**Issue by RoopeHakulinen** [ngx-translate/http-loader#16]
Change log for 1.0.0 refers only to the fact that the library is only compatible with Angular 4.3. What is should instead list as breaking change is that it now uses `HttpClient` instead of old `Http`. This is a breaking change when you have for example the following code:

```
export function createTranslateLoader(http: Http) {
  return new TranslateHttpLoader(http, './my-path', '.json');
}
```

this needs now to be refactored as follows:

```
export function createTranslateLoader(httpClient: HttpClient) {
  return new TranslateHttpLoader(httpClient, './my-path', '.json');
}
```

**Comment by ocombe** [comment]
True, I'll add a note, thanks

**Comment by RoopeHakulinen** [comment]
Awesome, much better. Thanks!
