### ISSUE TITLE
Incorrect peer dependencies

### ISSUE THREAD

**Issue by RoopeHakulinen** [ngx-translate/http-loader#17]
In `package.json` there's the following block:

```
"peerDependencies": {
  "@ngx-translate/core": ">=6.0.0",
  "@angular/core": ">=4.3.1",
  "@angular/http": ">=4.3.1"
},
```

where there seems to be a _peerDependency_ for `@angular/http` which the package doesn't depend on anymore as it is now based on the new `HttpClient`. Instead _peerDependency_ should point to `@angular/common` which includes the `@angular/common/http` and thus the `HttpClient`.

While on the topic of _peerDependencies_, is _2.3.1_ the correct version to be required as it is already the _2.3.0_ that implements the `HttpClient`? Might be that there's some bug in 2.3.0 that was only fixed on 2.3.1.

**Comment by ocombe** [comment]
good point, can you make a PR to fix this please? And no, 4.3.0 is enough

**Comment by RoopeHakulinen** [comment]
Sure, just a sec.

**Comment by RoopeHakulinen** [comment]
Here you go: https://github.com/ngx-translate/http-loader/pull/18

**Comment by ocombe** [comment]
thanks
