### ISSUE TITLE
getTranslation not returning body of the Response object

### ISSUE THREAD

**Issue by mario-petrovic** [ngx-translate/http-loader#23]
Hello,

I don't know if this is overlooked, but i see that in commit [65001abd](https://github.com/ngx-translate/http-loader/commit/65001abd#diff-43c15434265da46040f5d8d262e35735R14) for 1.0.0 release .json() was removed. 

I guess that since http-loader is for general use, and that use is loading json files or any other REST call, which will go through http.get() call, it needs .json() to extract the data from the response.

Thank you.

Mario

**Comment by SamVerschueren** [comment]
It's not overlooked, the new `@angular/common/http` [HttpClient](https://angular.io/api/common/http/HttpClient) returns `json` by default and the `.json()` call doesn't exist anymore.

**Comment by mario-petrovic** [comment]
But i am getting Response object back in my component when i log result:

```
this._translateService.use('en_US').toPromise().then((res: any) => {
      console.log(this._translateService.translations);
});
```

**Comment by SamVerschueren** [comment]
Are you using the new `@angular/common/http` HttpClient or not? From the docs:

> NB: if you're still on Angular <4.3, please use Http from @angular/http with http-loader@0.1.0.

So if you are using the "old" `@angular/http`, make sure you are using `http-loader@0.1.0`.

**Comment by mario-petrovic** [comment]
Yea, i saw that, and i went for the last version with HttpClient. This is my code in the module:

```
import { HttpClient } from '@angular/common/http';

export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, 'app/' , '.json');
}

@NgModule({
    imports: [
        TranslateModule.forChild({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [Http],
            },
            isolate: true
        })
    ]
})
```

Ahhh. I got Http left in deps. I have that custom interceptor with Http, i guess that is what was wrong.

**Comment by SamVerschueren** [comment]
Jep, you have to pass `HttpClient` in your `deps` list.

**Comment by mario-petrovic** [comment]
Thanks for your help Sam.

Cheers.

**Comment by SamVerschueren** [comment]
No problem, glad it works :)
