### ISSUE TITLE
Is this actually being supported?

### ISSUE THREAD

**Issue by kamok** [ngx-translate/http-loader#3]
I'm not sure if the docs are complete. Is the loader ready to use? How do I configure it to make the HTTP call to my server to fetch the translation JSON file?

**Comment by ocombe** [comment]
The docs are in the readme: https://github.com/ngx-translate/http-loader/blob/master/README.md
That's like the front page of this repository.

What don't you understand? The example seems quite clear to me.

**Comment by kamok** [comment]
From my understanding, this loader, instead of the static loader that pulls a `.json` from your local machine, makes an HTTP GET request to an external server for the `.json` and loads it onto my ng2 app. If so, where does it say in the docs how to make the HTTP call? 

All I see is that you're loading it from your local client app in `/assets/i18n/en.json`. Am I not understanding how this works?

**Comment by kamok** [comment]
Like I have this set up already:

```
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets', '.json'),
      deps: [Http]
    })
```

And it pulls my `en.json` from `assets/en.json`. Isn't the HTTP loader suppose to fetch it from another server, like "http://service.mycompany.com/translation`. Why would I use this instead of the `TranslateStaticLoader`

**Comment by ocombe** [comment]
Yes, you don't have to do anything to make the request, once ngx-translated is configured to use this loader it will automatically request the files via http when it needs translations (usually when you call .use() or when you change the language)

**Comment by ocombe** [comment]
If you need to load them from another server you can use a complete path instead of just "/assets", in your case that would be "http://service.mycompany.com/translation/"

**Comment by kamok** [comment]
Thanks for your help. I was expecting a more robust system that allows you to specify what lang is wanted, and make the module `GET` the data from a different path accordingly. I'll write my own custom Loader to achieve this end, as I would also need to save the translations on Storage for an offline feature. (using Ionic). Closed.

**Comment by ocombe** [comment]
Yes this is a very basic implementation, I highly encourage people to write their own loaders if they have specific needs and offline storage is a good example (I've done it myself in my custom loader on an app I was working on).
