### ISSUE TITLE
Latest angular (5.x) support

### ISSUE THREAD

**Issue by wesleycoder** [ngx-translate/http-loader#32]
I'm using @angular/common ^5.1.0-rc.0.

My build breaks on production with `npm ERR! peerinvalid Peer @ngx-translate/http-loader@2.0.0 wants @angular/common@>=4.3.0`

Would be nice if the peerDependencies was something like ` "@angular/common": ">=4.3.0 || >=5.0.0"`

**Comment by ocombe** [comment]
Are you still using npm 2? With npm 3 ">=4.3.0" should also include 5.x

**Comment by wesleycoder** [comment]
I'm actually using yarn locally.
The thing is that my project is a Ionic app that is being built with the [Ionic Pro](https://dashboard.ionicjs.com) service that uses npm  v2.15.12.
Any workarounds for this?

**Comment by wesleycoder** [comment]
Just to clarify, why do you use `>=` instead of `^` when `^` being the default for npm and it gives more flexibility?

**Comment by wesleycoder** [comment]
I think that it will not be needed anymore.
There's no documentation, but I tried specifying the `npm` version in the `package.json` and the build passed.
```js
// ...
  "engines" : {
    "node" : "^8.0.0",
    "npm" : "^3.0.0"
  },
// ...
```
It seems that Ionic Pro supports `engines` in `package.json`, but there is no documentation about it.

**Comment by ocombe** [comment]
> Just to clarify, why do you use >= instead of ^ when ^ being the default for npm and it gives more flexibility?

for that kind of reasons, because `^` means the current major only (^4.x), when `>=` means the current major and the next majors as well
You can test the different options here: https://semver.npmjs.com/

**Comment by wesleycoder** [comment]
Oh, I didn't have that in mind.
I'll put this in my "research later" list :no_mouth:.

Confirmed that `engine` actually works.
Checking the build log I found:
```bash
npm info using npm@5.3.0
npm info using node@v8.2.1
```
I've made a request on the [Ionic Forum](https://forum.ionicframework.com/t/ionic-pro-supporting-engines-on-package-json/114599) about documenting this behavior
