### ISSUE TITLE
No option to set headers

### ISSUE THREAD

**Issue by woteska** [ngx-translate/http-loader#38]
**Hi!**

I can't get any .json, because there is not option to set up headers to requests.
Now, I can solve it within .htaccess file, but it is not a real solution. I would be glad if I could set headers to requests.:)

**Connection with:**
https://github.com/ngx-translate/http-loader/issues/9
https://github.com/ngx-translate/http-loader/pull/19

**Comment by ocombe** [comment]
No need to open a new issue for that, thanks.

**Comment by woteska** [comment]
Okay, I am sorry, but the pull was on Aug 1 2017, the issue on Jun 30 2017, and from that days nothing happened, noting wasn't been merged. :/ So I thought that these are dead posts.

**Comment by ocombe** [comment]
Yes, I'm closing those.
