### ISSUE TITLE
ngx-translate access other baseurl

### ISSUE THREAD

**Issue by pbkh-bunthai** [ngx-translate/http-loader#56]
I use this url to load my Login Ui: [http://localhost:5000/login](http://localhost:5000/login). 
But in console, it printed error: [http://localhost:8081/api/assets/i18n/ja.json](http://localhost:8081/api/assets/i18n/ja.json) 401 (Unauthorized). 
It access to my api url. 
It should be access this url [http://localhost:5000/assets/i18n/ja.json](http://localhost:5000/assets/i18n/ja.json) instead.
I do a simple configuration.

```
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
```
I found this configuration in my project:

```
{
  "bffBaseUrl": "http://localhost:8081"
}
```
How can I make it access to [http://localhost:5000/assets/i18n/ja.json]( http://localhost:5000/assets/i18n/ja.json) ?

**Comment by aicokleinovink** [comment]
I run into the same problem, what was your solution here??

**Comment by pbkh-bunthai** [comment]
@aicokleinovink 

I used this way, it's working fine:

```
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, window.location.origin + '/assets/i18n/json/', '.json');
}
```

I hope it work for you! :)
