### ISSUE TITLE
Giving error with Http Library

### ISSUE THREAD

**Issue by mariohmol** [ngx-translate/http-loader#7]
Hi there.

i had ng2-translate working in a ionic3 project and i'm trying to upgrade to the ngx-translate.

When i try to follow this readme, i'm getting this error:

```
Argument of type 'Http' is not assignable to parameter of type 'Http'. Property '_backend' is protected but
            type 'Http' is not a class derived from 'Http'.

     L114:  export function HttpLoaderFactory(http: Http) {
     L115:      return new TranslateHttpLoader(http);
```

As a workaround o copied the TranslateHttpLoader from this repo and pasted in my project.

Maybe need to upgrade the angular version from the package.json from this project?
Here i'm using `angular 4.1.2`and its working pretty good.

Thanks

**Comment by tplk** [comment]
@mariohmol Check where Http class is imported from.
Related issue: https://github.com/angular/angular/issues/11801

**Comment by mariohmol** [comment]
@t-p-l-k seems to be the same thing.. the import is `import { Http } from '@angular/http';` .. 

that issue is closed but its still giving the error..

**Comment by bleuscyther** [comment]
i think it's expecting **HttpClient**
``` javascript
export declare class TranslateHttpLoader implements TranslateLoader {
...
constructor(http: HttpClient, prefix?: string, suffix?: string);

...
```

**Comment by SamVerschueren** [comment]
You should use the new Http client

```
import {HttpClientModule, HttpClient} from '@angular/common/http';
```

It's in the docs. 

[Edit] docs are actually quite confusing. There's an open issue for the docs.

**Comment by SamVerschueren** [comment]
That new Http module is only available since Angular@4.3, if you're using an older version, just use the older loader ngx-translate/http-loader@0.1.0

**Comment by bleuscyther** [comment]
@SamVerschueren i think there is an issue with angular 4.3 and the new packages,  can the demo in the website be updated ?

**Comment by SamVerschueren** [comment]
It works for me. Do you mean the plunkr?

**Comment by bleuscyther** [comment]
yes

**Comment by DacostaDesarrollo** [comment]
https://stackoverflow.com/questions/45372318/argument-of-type-http-is-not-assignable-to-parameter-of-type-http-in-ionic-n
