### ISSUE TITLE
5.0.0 has no tag on GitHub and no release

### ISSUE THREAD

**Issue by williamdes** [ngx-translate/http-loader#76]
https://github.com/ngx-translate/http-loader/releases

https://github.com/ngx-translate/http-loader/tags

Also: please add a CHANGELOG.md ;)

**Comment by pascaliske** [comment]
It seems there are only 3 commits between the release of **v4.0.0** and **master** which I assume to be the base of the npm release **v5.0.0**: https://github.com/ngx-translate/http-loader/compare/v4.0.0...master

**EDIT:** But surely it would be good if there were a tag or release on GitHub. 😉

**Comment by williamdes** [comment]
@ocombe did you see this one ?

**Comment by ocombe** [comment]
Releases added, not sure why commitizen stopped updating the releases automatically
