### ISSUE TITLE
ES5 not supported anymore since version 5

### ISSUE THREAD

**Issue by vdlindk** [ngx-translate/http-loader#79]
Why is ES5 not supported anymore. As a consequence we aren't able tot support IE11 anymore (which is still our company browser)

**Comment by ocombe** [comment]
Hello, because Angular v10 doesn't support IE11 (and ES5) anymore

**Comment by vdlindk** [comment]
thanks for the feedback ... another argument that we can contribute to the discussion on replacing our company browser

**Comment by liesahead** [comment]
@ocombe , But angular 10 still supports IE9, IE10 and IE11. It will drop support for IE9 and IE10 in angular11. It will continue to support IE11, so I think this issue should be reopened.

**Comment by liesahead** [comment]
@ocombe , actually, angular supports IE9-IE11, it will only drop support for IE9 and IE10 in angular11, but will continue to support IE11.

**Comment by ocombe** [comment]
You are right, Angular still supports IE11, but according to the update guide for v10:

> The Angular Package Format has been updated to remove esm5 and fesm5 formats. These are no longer distributed in our npm packages. If you don't use the CLI, you may need to downlevel Angular code to ES5 yourself.

And in the [Angular package format for v10](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) you can find the following text:
> ES2015 Language level is now the default language level that is consumed by Angular CLI and other tooling.
If applications still need to support ES5 browsers, then Angular CLI can downlevel the bundle to ES5 at application build time via differential loading and builds feature.

**Comment by liesahead** [comment]
@ocombe , I just misunderstood what you meant then 🙂 whatever, our team has no problems with http-loader as it works as good as before even in IE11.
