### ISSUE TITLE
Update @ngx-translate/core peer dependency.

### ISSUE THREAD

**Issue by tplk** [ngx-translate/http-loader#8]
```
npm WARN @ngx-translate/http-loader@0.0.3 requires a peer of 
@ngx-translate/core@^6.0.0 but none was installed.
```
Since core 7.0.0 was released http-loader's peer dependency needs to be updated.

**Comment by ocombe** [comment]
Well >=6.0.0 should work with v7, doesn't it?

**Comment by tplk** [comment]
@ocombe current entry in package.json: ```"@ngx-translate/core": "^6.0.0"```
So 7.0.0 doesn't match.
But it's just an aesthetics concern really, nothing's broken.

**Comment by t-p-l-k** [comment]
Wait.

**Comment by tplk** [comment]
v0.0.3 doesn't include your last commit on master where you update dependencies.
https://github.com/ngx-translate/http-loader/commit/6d5c832e00b0c806f55c6f4d3539358a5ee16567
Is there a reason why it wasn't released yet?

**Comment by ocombe** [comment]
hmm, because I used "chore" in my commit msg :)
